consumer_items:
  vehicles:
    - bicycle
    - car
    - motorcycle
    - airplane
    - bus
    - train
    - truck
    - boat
  street_objects:
    - traffic light
    - fire hydrant
    - stop sign
    - parking meter
    - bench
  animals:
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe
  accessories:
    - backpack
    - umbrella
    - handbag
    - tie
    - suitcase
  sports:
    - frisbee
    - skis
    - snowboard
    - sports ball
    - kite
    - baseball bat
    - baseball glove
    - skateboard
    - surfboard
    - tennis racket
  kitchen_items:
    - bottle
    - wine glass
    - cup
    - fork
    - knife
    - spoon
    - bowl
    - banana
    - apple
    - sandwich
    - orange
    - broccoli
    - carrot
    - hot dog
    - pizza
    - donut
    - cake
  furniture:
    - chair
    - couch
    - potted plant
    - bed
    - dining table
    - toilet
  electronics:
    - tv
    - laptop
    - mouse
    - remote
    - keyboard
    - cell phone
    - microwave
    - oven
    - toaster
    - sink
    - refrigerator
  misc:
    - book
    - clock
    - vase
    - scissors
    - teddy bear
    - hair drier
    - toothbrush
